### ISSUE TITLE
output of convolution has wrong dimensionality

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#420] opened 2023-09-27 12:40 UTC
In the image of the convolution kernel sliding across a synthetic image, the output has dimensionality `(3,4)` whereas it should be `(3,3)`.

![](https://carpentries-incubator.github.io/deep-learning-intro/fig/04_conv_matrix.png) 

I am not sure if the original svg or tex or ... file is still available.

**Comment by svenvanderburg** [comment] 2023-09-27 13:53
Duplicate of #392

**Closed by svenvanderburg** 2023-09-27 13:53 UTC
